<?php

namespace App\Actions\Payroll;

use App\Enums\PayRunStatus;
use App\Models\EmployeePayrollProfile;
use App\Models\PayRun;
use App\Models\TimeEntry;
use App\Services\Payroll\CalculatePayRun;
use App\Services\Posting\DocumentNumberGenerator;
use App\Support\Payroll\BankedOvertimeRules;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use RuntimeException;

/**
 * Creates or updates a DRAFT pay run: the header (schedule + period + pay date +
 * bank) and the per-employee lines (which employees and their hours). Does NOT
 * calculate deductions or post — that is {@see CalculatePayRun}.
 *
 * Only draft/calculated runs may be edited; a posted run must be voided and
 * recreated.
 *
 * Expected $data shape:
 *   payroll_schedule_id: ?int
 *   period_start_date:   string (Y-m-d)
 *   period_end_date:     string (Y-m-d)
 *   pay_date:            string (Y-m-d)
 *   bank_account_id:     ?int
 *   lines: array<int, array{
 *     contact_id: int,
 *     hours_worked?: float|string|null,
 *     manual_earnings?: array<int, array{code: string, name: string, calc_kind: string,
 *       amount_cents?: ?int, hours?: ?float, multiplier_bp?: int, expense_account_id?: ?int, t4_box?: ?string}>
 *   }>
 *
 * manual_earnings covers OPERATOR rows only; rows generated by
 * {@see PullTimeEntriesIntoPayRun} (source='time_entries') are never replaced here.
 */
final class SavePayRun
{
    public function __construct(private DocumentNumberGenerator $numbers) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public function handle(array $data, ?PayRun $payRun = null): PayRun
    {
        return DB::transaction(function () use ($data, $payRun): PayRun {
            $company = app('current_company');

            if ($payRun && $payRun->exists && ! $payRun->status->isEditable()) {
                throw new RuntimeException('Only draft pay runs can be edited.');
            }

            $header = [
                'payroll_schedule_id' => $data['payroll_schedule_id'] ?? null,
                'period_start_date' => $data['period_start_date'],
                'period_end_date' => $data['period_end_date'],
                'pay_date' => $data['pay_date'],
                'bank_account_id' => $data['bank_account_id'] ?? null,
            ];

            if ($payRun && $payRun->exists) {
                $payRun->update($header);
            } else {
                $payRun = PayRun::create($header + [
                    'run_no' => $this->numbers->next($company, PayRun::class, 'run_no', 'PR'),
                    'status' => PayRunStatus::Draft,
                ]);
            }

            $keptLineIds = [];

            foreach (array_values($data['lines'] ?? []) as $lineData) {
                $profile = EmployeePayrollProfile::query()
                    ->where('contact_id', $lineData['contact_id'])
                    ->firstOrFail();

                $hours = isset($lineData['hours_worked']) && $lineData['hours_worked'] !== ''
                    ? (float) $lineData['hours_worked']
                    : null;

                $line = $payRun->lines()->updateOrCreate(
                    ['contact_id' => $lineData['contact_id']],
                    [
                        'employee_payroll_profile_id' => $profile->id,
                        'province_of_employment' => $profile->province_of_employment,
                        'pay_basis' => $profile->pay_basis,
                        'hours_worked' => $hours,
                        'hourly_rate_cents' => $profile->hourly_rate_cents,
                        'annual_salary_cents' => $profile->annual_salary_cents,
                    ],
                );

                // Run-time one-off earnings (overtime/bonus/commission). Replaced
                // wholesale when sent; left untouched when the key is absent.
                // Rows the time-entry pull generated (source='time_entries') are
                // owned by the pull, not the form — they survive a save and are
                // only replaced by a re-pull.
                if (array_key_exists('manual_earnings', $lineData)) {
                    $line->manualEarnings()->whereNull('source')->delete();

                    foreach (array_values($lineData['manual_earnings']) as $index => $me) {
                        // Banking is gated per employee (profile toggle, province,
                        // written agreement) — reject at save so the operator gets
                        // a field error instead of a calculation-time exception.
                        if (($me['code'] ?? '') === 'overtime_banked' && ! BankedOvertimeRules::canBank($profile)) {
                            throw ValidationException::withMessages([
                                'rows' => __(':name cannot bank overtime — enable it on their payroll profile (province permitting, with a written-agreement date).', ['name' => $profile->contact->display_name]),
                            ]);
                        }
                        $line->manualEarnings()->create([
                            'code' => $me['code'],
                            'name' => $me['name'],
                            'calc_kind' => $me['calc_kind'] ?? 'amount',
                            'amount_cents' => $me['amount_cents'] ?? null,
                            'hours' => $me['hours'] ?? null,
                            'multiplier_bp' => $me['multiplier_bp'] ?? 10000,
                            'expense_account_id' => $me['expense_account_id'] ?? null,
                            't4_box' => $me['t4_box'] ?? null,
                            'line_order' => $index,
                        ]);
                    }
                }

                $keptLineIds[] = $line->id;
            }

            // Drop lines for employees no longer in the run — releasing their
            // pulled time entries first, or the stamps leak forever (the pull
            // skips stamped entries and only a re-pull of THIS run or a void
            // releases them; a posted run never would).
            $droppedContactIds = $payRun->lines()->whereNotIn('id', $keptLineIds)->pluck('contact_id');

            if ($droppedContactIds->isNotEmpty()) {
                TimeEntry::query()
                    ->where('pay_run_id', $payRun->id)
                    ->whereIn('contact_id', $droppedContactIds)
                    ->update(['pay_run_id' => null]);
            }

            $payRun->lines()->whereNotIn('id', $keptLineIds)->delete();

            // Editing the line-up invalidates any prior calculation.
            $payRun->forceFill(['status' => PayRunStatus::Draft])->save();

            return $payRun->refresh();
        });
    }
}
