<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Links a bill back to the purchase order it (partially) bills against. Set once
     * when a bill is generated by fulfilling a PO; immutable thereafter so an edit
     * can't orphan the PO's fulfillment tracking. Mirror of invoices.sales_order_id.
     */
    public function up(): void
    {
        Schema::table('bills', function (Blueprint $table) {
            $table->foreignId('purchase_order_id')->nullable()->after('contact_id')
                ->constrained('purchase_orders')->nullOnDelete();
            $table->index(['company_id', 'purchase_order_id']);
        });
    }

    public function down(): void
    {
        Schema::table('bills', function (Blueprint $table) {
            $table->dropIndex(['company_id', 'purchase_order_id']);
            $table->dropConstrainedForeignId('purchase_order_id');
        });
    }
};
