<?php

namespace App\Models;

use App\Concerns\BelongsToCompany;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

#[Fillable([
    'company_id', 'pay_run_line_id', 'code', 'name', 'calc_kind',
    'amount_cents', 'hours', 'multiplier_bp', 'expense_account_id', 't4_box', 'line_order', 'source',
])]
class PayRunLineManualEarning extends Model
{
    use BelongsToCompany, HasFactory;

    /**
     * source value marking rows generated by the time-entry pull (vs rows an
     * operator entered by hand on the run).
     */
    public const SOURCE_TIME_ENTRIES = 'time_entries';

    /**
     * @return BelongsTo<PayRunLine, $this>
     */
    public function payRunLine(): BelongsTo
    {
        return $this->belongsTo(PayRunLine::class);
    }

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'amount_cents' => 'integer',
            'hours' => 'decimal:2',
            'multiplier_bp' => 'integer',
            'line_order' => 'integer',
        ];
    }
}
